//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MyProto.proto
namespace proto.MyProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StateCode")]
  public partial class StateCode : global::ProtoBuf.IExtensible
  {
    public StateCode() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }

    private string _message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterReq")]
  public partial class RegisterReq : global::ProtoBuf.IExtensible
  {
    public RegisterReq() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }

    private string _deviceID = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"deviceID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deviceID
    {
      get { return _deviceID; }
      set { _deviceID = value; }
    }

    private string _channel = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerInfo")]
  public partial class ServerInfo : global::ProtoBuf.IExtensible
  {
    public ServerInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _serverName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serverName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverName
    {
      get { return _serverName; }
      set { _serverName = value; }
    }
    private string _serverIp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"serverIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverIp
    {
      get { return _serverIp; }
      set { _serverIp = value; }
    }
    private ServerInfo.StateType _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ServerInfo.StateType type
    {
      get { return _type; }
      set { _type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"StateType")]
    public enum StateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNBLOCKED", Value=0)]
      UNBLOCKED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CROWD", Value=1)]
      CROWD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLOCKED", Value=2)]
      BLOCKED = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerRes")]
  public partial class ServerRes : global::ProtoBuf.IExtensible
  {
    public ServerRes() {}
    
    private readonly global::System.Collections.Generic.List<ServerInfo> _servers = new global::System.Collections.Generic.List<ServerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"servers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ServerInfo> servers
    {
      get { return _servers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterRes")]
  public partial class RegisterRes : global::ProtoBuf.IExtensible
  {
    public RegisterRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _serverIp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"serverIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverIp
    {
      get { return _serverIp; }
      set { _serverIp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRes")]
  public partial class LoginRes : global::ProtoBuf.IExtensible
  {
    public LoginRes() {}
    
    private int _accountId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetPlayerInfosReq")]
  public partial class GetPlayerInfosReq : global::ProtoBuf.IExtensible
  {
    public GetPlayerInfosReq() {}
    
    private int _accountId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetPlayerInfosRes")]
  public partial class GetPlayerInfosRes : global::ProtoBuf.IExtensible
  {
    public GetPlayerInfosRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private readonly global::System.Collections.Generic.List<PlayerInfo> _infos = new global::System.Collections.Generic.List<PlayerInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlayerInfo> infos
    {
      get { return _infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreatePlayerInfoReq")]
  public partial class CreatePlayerInfoReq : global::ProtoBuf.IExtensible
  {
    public CreatePlayerInfoReq() {}
    
    private string _accountId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreatePlayerInfoRes")]
  public partial class CreatePlayerInfoRes : global::ProtoBuf.IExtensible
  {
    public CreatePlayerInfoRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private PlayerInfo _info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PlayerInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectPlayerReq")]
  public partial class SelectPlayerReq : global::ProtoBuf.IExtensible
  {
    public SelectPlayerReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _gameServerIp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gameServerIp
    {
      get { return _gameServerIp; }
      set { _gameServerIp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropInfo")]
  public partial class PropInfo : global::ProtoBuf.IExtensible
  {
    public PropInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _propId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"propId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int propId
    {
      get { return _propId; }
      set { _propId = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _slot;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerStateInfo")]
  public partial class PlayerStateInfo : global::ProtoBuf.IExtensible
  {
    public PlayerStateInfo() {}
    
    private int _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _localtion = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"localtion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> localtion
    {
      get { return _localtion; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRoleInfo")]
  public partial class PlayerRoleInfo : global::ProtoBuf.IExtensible
  {
    public PlayerRoleInfo() {}
    
    private PlayerInfo _info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PlayerInfo info
    {
      get { return _info; }
      set { _info = value; }
    }
    private readonly global::System.Collections.Generic.List<PropInfo> _bagInfo = new global::System.Collections.Generic.List<PropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bagInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropInfo> bagInfo
    {
      get { return _bagInfo; }
    }
  

    private int _bloodStore = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bloodStore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bloodStore
    {
      get { return _bloodStore; }
      set { _bloodStore = value; }
    }

    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private int _gem = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gem", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gem
    {
      get { return _gem; }
      set { _gem = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimeInfo")]
  public partial class TimeInfo : global::ProtoBuf.IExtensible
  {
    public TimeInfo() {}
    
    private long _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectPlayerRes")]
  public partial class SelectPlayerRes : global::ProtoBuf.IExtensible
  {
    public SelectPlayerRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private PlayerRoleInfo _roleInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PlayerRoleInfo roleInfo
    {
      get { return _roleInfo; }
      set { _roleInfo = value; }
    }
    private PlayerStateInfo _stateInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"stateInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PlayerStateInfo stateInfo
    {
      get { return _stateInfo; }
      set { _stateInfo = value; }
    }
    private TimeInfo _time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TimeInfo time
    {
      get { return _time; }
      set { _time = value; }
    }
    private readonly global::System.Collections.Generic.List<SignInInfo> _infos = new global::System.Collections.Generic.List<SignInInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SignInInfo> infos
    {
      get { return _infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignInInfo")]
  public partial class SignInInfo : global::ProtoBuf.IExtensible
  {
    public SignInInfo() {}
    
    private TimeInfo _time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TimeInfo time
    {
      get { return _time; }
      set { _time = value; }
    }
    private int _signId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int signId
    {
      get { return _signId; }
      set { _signId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignInReq")]
  public partial class SignInReq : global::ProtoBuf.IExtensible
  {
    public SignInReq() {}
    
    private TimeInfo _SignInTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SignInTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TimeInfo SignInTime
    {
      get { return _SignInTime; }
      set { _SignInTime = value; }
    }
    private int _signId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int signId
    {
      get { return _signId; }
      set { _signId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignInRes")]
  public partial class SignInRes : global::ProtoBuf.IExtensible
  {
    public SignInRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private TimeInfo _serverTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"serverTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public TimeInfo serverTime
    {
      get { return _serverTime; }
      set { _serverTime = value; }
    }
    private readonly global::System.Collections.Generic.List<PropInfo> _propInfo = new global::System.Collections.Generic.List<PropInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"propInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropInfo> propInfo
    {
      get { return _propInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BagInfoReq")]
  public partial class BagInfoReq : global::ProtoBuf.IExtensible
  {
    public BagInfoReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BagInfoRes")]
  public partial class BagInfoRes : global::ProtoBuf.IExtensible
  {
    public BagInfoRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private readonly global::System.Collections.Generic.List<PropInfo> _bagInfo = new global::System.Collections.Generic.List<PropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bagInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropInfo> bagInfo
    {
      get { return _bagInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipPropInfo")]
  public partial class EquipPropInfo : global::ProtoBuf.IExtensible
  {
    public EquipPropInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _propId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"propId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int propId
    {
      get { return _propId; }
      set { _propId = value; }
    }
    private int _slot;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int slot
    {
      get { return _slot; }
      set { _slot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BagInfoEquipReq")]
  public partial class BagInfoEquipReq : global::ProtoBuf.IExtensible
  {
    public BagInfoEquipReq() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private readonly global::System.Collections.Generic.List<EquipPropInfo> _equipedProps = new global::System.Collections.Generic.List<EquipPropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"equipedProps", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EquipPropInfo> equipedProps
    {
      get { return _equipedProps; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BagInfoEquipRes")]
  public partial class BagInfoEquipRes : global::ProtoBuf.IExtensible
  {
    public BagInfoEquipRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private readonly global::System.Collections.Generic.List<PropInfo> _propInfos = new global::System.Collections.Generic.List<PropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"propInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropInfo> propInfos
    {
      get { return _propInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserPropInfo")]
  public partial class UserPropInfo : global::ProtoBuf.IExtensible
  {
    public UserPropInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UsePropReq")]
  public partial class UsePropReq : global::ProtoBuf.IExtensible
  {
    public UsePropReq() {}
    
    private readonly global::System.Collections.Generic.List<UserPropInfo> _props = new global::System.Collections.Generic.List<UserPropInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"props", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UserPropInfo> props
    {
      get { return _props; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UsePropRes")]
  public partial class UsePropRes : global::ProtoBuf.IExtensible
  {
    public UsePropRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private readonly global::System.Collections.Generic.List<PropInfo> _bagInfo = new global::System.Collections.Generic.List<PropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bagInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropInfo> bagInfo
    {
      get { return _bagInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnchancePropReq")]
  public partial class EnchancePropReq : global::ProtoBuf.IExtensible
  {
    public EnchancePropReq() {}
    
    private int _enchangeId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"enchangeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int enchangeId
    {
      get { return _enchangeId; }
      set { _enchangeId = value; }
    }
    private readonly global::System.Collections.Generic.List<UserPropInfo> _props = new global::System.Collections.Generic.List<UserPropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"props", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UserPropInfo> props
    {
      get { return _props; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnchancePropRes")]
  public partial class EnchancePropRes : global::ProtoBuf.IExtensible
  {
    public EnchancePropRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private readonly global::System.Collections.Generic.List<PropInfo> _bagInfo = new global::System.Collections.Generic.List<PropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bagInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropInfo> bagInfo
    {
      get { return _bagInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterDungeonsReq")]
  public partial class EnterDungeonsReq : global::ProtoBuf.IExtensible
  {
    public EnterDungeonsReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _dungeons;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dungeons", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dungeons
    {
      get { return _dungeons; }
      set { _dungeons = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterDungeonsRes")]
  public partial class EnterDungeonsRes : global::ProtoBuf.IExtensible
  {
    public EnterDungeonsRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private PlayerStateInfo _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PlayerStateInfo state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FinishDungeonsReq")]
  public partial class FinishDungeonsReq : global::ProtoBuf.IExtensible
  {
    public FinishDungeonsReq() {}
    
    private PlayerStateInfo _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PlayerStateInfo state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _monsterId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"monsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int monsterId
    {
      get { return _monsterId; }
      set { _monsterId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FinishDungeonsRes")]
  public partial class FinishDungeonsRes : global::ProtoBuf.IExtensible
  {
    public FinishDungeonsRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private readonly global::System.Collections.Generic.List<PropInfo> _newProps = new global::System.Collections.Generic.List<PropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"newProps", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropInfo> newProps
    {
      get { return _newProps; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyPropReq")]
  public partial class BuyPropReq : global::ProtoBuf.IExtensible
  {
    public BuyPropReq() {}
    
    private int _storeId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"storeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int storeId
    {
      get { return _storeId; }
      set { _storeId = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuyPropRes")]
  public partial class BuyPropRes : global::ProtoBuf.IExtensible
  {
    public BuyPropRes() {}
    
    private StateCode _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public StateCode code
    {
      get { return _code; }
      set { _code = value; }
    }
    private readonly global::System.Collections.Generic.List<PropInfo> _bagInfo = new global::System.Collections.Generic.List<PropInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bagInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PropInfo> bagInfo
    {
      get { return _bagInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MessageId")]
    public enum MessageId
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERegisterReq", Value=1001)]
      ERegisterReq = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERegisterRes", Value=1002)]
      ERegisterRes = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EServerRes", Value=1003)]
      EServerRes = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ELoginReq", Value=1006)]
      ELoginReq = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ELoginRes", Value=1007)]
      ELoginRes = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGetPlayerInfosReq", Value=1008)]
      EGetPlayerInfosReq = 1008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EGetPlayerInfosRes", Value=1009)]
      EGetPlayerInfosRes = 1009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECreatePlayerInfoReq", Value=1010)]
      ECreatePlayerInfoReq = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECreatePlayerInfoRes", Value=1011)]
      ECreatePlayerInfoRes = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESelectPlayerReq", Value=1012)]
      ESelectPlayerReq = 1012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESelectPlayerRes", Value=1013)]
      ESelectPlayerRes = 1013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESignInReq", Value=1014)]
      ESignInReq = 1014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESignInRes", Value=1015)]
      ESignInRes = 1015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EBagInfoEquipReq", Value=1016)]
      EBagInfoEquipReq = 1016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EBagInfoEquipRes", Value=1017)]
      EBagInfoEquipRes = 1017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EBagInfoReq", Value=1018)]
      EBagInfoReq = 1018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EBagInfoRes", Value=1019)]
      EBagInfoRes = 1019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EUsePropReq", Value=1020)]
      EUsePropReq = 1020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EUsePropRes", Value=1021)]
      EUsePropRes = 1021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EEnchancePropReq", Value=1022)]
      EEnchancePropReq = 1022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EEnchancePropRes", Value=1023)]
      EEnchancePropRes = 1023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EEnterDungeonsReq", Value=1024)]
      EEnterDungeonsReq = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EEnterDungeonsRes", Value=1025)]
      EEnterDungeonsRes = 1025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EFinishDungeonsReq", Value=1026)]
      EFinishDungeonsReq = 1026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EFinishDungeonsRes", Value=1027)]
      EFinishDungeonsRes = 1027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EBuyPropReq", Value=1028)]
      EBuyPropReq = 1028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EBuyPropRes", Value=1029)]
      EBuyPropRes = 1029
    }
  
}