//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: client.proto
// Note: requires additional types generated from: common.proto
namespace client
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientMsg")]
  public partial class ClientMsg : global::ProtoBuf.IExtensible
  {
    public ClientMsg() {}
    
    private uint _UID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UID
    {
      get { return _UID; }
      set { _UID = value; }
    }
    private uint _ErrorCode = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ErrorCode
    {
      get { return _ErrorCode; }
      set { _ErrorCode = value; }
    }
    private string _Time = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private client.ReqRegister _Register = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Register", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.ReqRegister Register
    {
      get { return _Register; }
      set { _Register = value; }
    }
    private client.ReqLogin _Login = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Login", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.ReqLogin Login
    {
      get { return _Login; }
      set { _Login = value; }
    }
    private client.ReqPraticeLevel _PraticeLevel = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"PraticeLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.ReqPraticeLevel PraticeLevel
    {
      get { return _PraticeLevel; }
      set { _PraticeLevel = value; }
    }
    private client.ReqActualCombat _ActualCombat = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ActualCombat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.ReqActualCombat ActualCombat
    {
      get { return _ActualCombat; }
      set { _ActualCombat = value; }
    }
    private client.ReqCancelMatch _CancelMatch = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"CancelMatch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.ReqCancelMatch CancelMatch
    {
      get { return _CancelMatch; }
      set { _CancelMatch = value; }
    }
    private client.ReqReady _Ready = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Ready", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.ReqReady Ready
    {
      get { return _Ready; }
      set { _Ready = value; }
    }
    private client.ReqExitLevel _ExitLevel = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"ExitLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.ReqExitLevel ExitLevel
    {
      get { return _ExitLevel; }
      set { _ExitLevel = value; }
    }
    private client.ReqRoleBorn _RoleBorn = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"RoleBorn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.ReqRoleBorn RoleBorn
    {
      get { return _RoleBorn; }
      set { _RoleBorn = value; }
    }
    private client.ReqMove _RoleMove = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"RoleMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.ReqMove RoleMove
    {
      get { return _RoleMove; }
      set { _RoleMove = value; }
    }
    private client.ReqAttack _RoleAttack = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"RoleAttack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public client.ReqAttack RoleAttack
    {
      get { return _RoleAttack; }
      set { _RoleAttack = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRegister")]
  public partial class ReqRegister : global::ProtoBuf.IExtensible
  {
    public ReqRegister() {}
    
    private string _Account = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqLogin")]
  public partial class ReqLogin : global::ProtoBuf.IExtensible
  {
    public ReqLogin() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqPraticeLevel")]
  public partial class ReqPraticeLevel : global::ProtoBuf.IExtensible
  {
    public ReqPraticeLevel() {}
    
    private uint _PlayerNumber = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PlayerNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PlayerNumber
    {
      get { return _PlayerNumber; }
      set { _PlayerNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqActualCombat")]
  public partial class ReqActualCombat : global::ProtoBuf.IExtensible
  {
    public ReqActualCombat() {}
    
    private uint _PlayerNumber = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PlayerNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PlayerNumber
    {
      get { return _PlayerNumber; }
      set { _PlayerNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCancelMatch")]
  public partial class ReqCancelMatch : global::ProtoBuf.IExtensible
  {
    public ReqCancelMatch() {}
    
    private common.LevelType _LevelType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"LevelType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.LevelType LevelType
    {
      get { return _LevelType; }
      set { _LevelType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqReady")]
  public partial class ReqReady : global::ProtoBuf.IExtensible
  {
    public ReqReady() {}
    
    private uint _HeroID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"HeroID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HeroID
    {
      get { return _HeroID; }
      set { _HeroID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqExitLevel")]
  public partial class ReqExitLevel : global::ProtoBuf.IExtensible
  {
    public ReqExitLevel() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqRoleBorn")]
  public partial class ReqRoleBorn : global::ProtoBuf.IExtensible
  {
    public ReqRoleBorn() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqMove")]
  public partial class ReqMove : global::ProtoBuf.IExtensible
  {
    public ReqMove() {}
    
    private common.Vector3 _dest = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.Vector3 dest
    {
      get { return _dest; }
      set { _dest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqAttack")]
  public partial class ReqAttack : global::ProtoBuf.IExtensible
  {
    public ReqAttack() {}
    
    private uint _skillID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillID
    {
      get { return _skillID; }
      set { _skillID = value; }
    }
    private uint _targetID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint targetID
    {
      get { return _targetID; }
      set { _targetID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}