//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common.proto
namespace common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgHead")]
  public partial class MsgHead : global::ProtoBuf.IExtensible
  {
    public MsgHead() {}
    
    private int _MsgId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"MsgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MsgId
    {
      get { return _MsgId; }
      set { _MsgId = value; }
    }
    private int _ActionId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ActionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ActionId
    {
      get { return _ActionId; }
      set { _ActionId = value; }
    }
    private int _ErrorCode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ErrorCode
    {
      get { return _ErrorCode; }
      set { _ErrorCode = value; }
    }
    private string _ErrorInfo;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ErrorInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ErrorInfo
    {
      get { return _ErrorInfo; }
      set { _ErrorInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3")]
  public partial class Vector3 : global::ProtoBuf.IExtensible
  {
    public Vector3() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleData")]
  public partial class RoleData : global::ProtoBuf.IExtensible
  {
    public RoleData() {}
    
    private uint _UniID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UniID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UniID
    {
      get { return _UniID; }
      set { _UniID = value; }
    }
    private uint _RoleID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RoleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint RoleID
    {
      get { return _RoleID; }
      set { _RoleID = value; }
    }
    private common.RoleType _RoleType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RoleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.RoleType RoleType
    {
      get { return _RoleType; }
      set { _RoleType = value; }
    }
    private common.RoleSide _RoleSide;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"RoleSide", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.RoleSide RoleSide
    {
      get { return _RoleSide; }
      set { _RoleSide = value; }
    }
    private int _Hp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Hp
    {
      get { return _Hp; }
      set { _Hp = value; }
    }
    private int _Mp = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Mp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Mp
    {
      get { return _Mp; }
      set { _Mp = value; }
    }
    private common.Vector3 _Pos = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.Vector3 Pos
    {
      get { return _Pos; }
      set { _Pos = value; }
    }
    private common.Vector3 _Dir = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Dir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.Vector3 Dir
    {
      get { return _Dir; }
      set { _Dir = value; }
    }
    private float _SightRange;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"SightRange", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float SightRange
    {
      get { return _SightRange; }
      set { _SightRange = value; }
    }
    private float _AttackRange;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"AttackRange", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float AttackRange
    {
      get { return _AttackRange; }
      set { _AttackRange = value; }
    }
    private common.Job _Job = common.Job.Brave;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"Job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(common.Job.Brave)]
    public common.Job Job
    {
      get { return _Job; }
      set { _Job = value; }
    }
    private common.RoleControl _RoleControl;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"RoleControl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.RoleControl RoleControl
    {
      get { return _RoleControl; }
      set { _RoleControl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MobileType")]
    public enum MobileType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=0)]
      Normal = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"iPod", Value=1)]
      iPod = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"iPad", Value=2)]
      iPad = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"iPhone", Value=3)]
      iPhone = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Phone_AppStore", Value=4)]
      Phone_AppStore = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Android", Value=5)]
      Android = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Mac", Value=6)]
      Mac = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WindowsPhone7", Value=7)]
      WindowsPhone7 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Unknow", Value=8)]
      Unknow = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LevelType")]
    public enum LevelType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Pratice", Value=0)]
      Pratice = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ActualCombat", Value=2)]
      ActualCombat = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoleType")]
    public enum RoleType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Hero", Value=0)]
      Hero = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Soldier", Value=1)]
      Soldier = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Monster", Value=2)]
      Monster = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Tower", Value=3)]
      Tower = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Doctor", Value=4)]
      Doctor = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Job")]
    public enum Job
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Brave", Value=0)]
      Brave = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Mage", Value=1)]
      Mage = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Hunter", Value=2)]
      Hunter = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Priest", Value=3)]
      Priest = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Bandit", Value=4)]
      Bandit = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Building", Value=11)]
      Building = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoleSide")]
    public enum RoleSide
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Blue", Value=1)]
      Blue = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Red", Value=-1)]
      Red = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Both", Value=2)]
      Both = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Neutrality", Value=0)]
      Neutrality = 0
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginGuideType")]
    public enum LoginGuideType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRole", Value=0)]
      CreateRole = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterWorld", Value=1)]
      EnterWorld = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoleControl")]
    public enum RoleControl
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Free", Value=0)]
      Free = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserControl", Value=1)]
      UserControl = 1
    }
  
}