//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: server.proto
// Note: requires additional types generated from: common.proto
namespace server
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerMsg")]
  public partial class ServerMsg : global::ProtoBuf.IExtensible
  {
    public ServerMsg() {}
    
    private uint _UID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UID
    {
      get { return _UID; }
      set { _UID = value; }
    }
    private uint _ErrorCode = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ErrorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ErrorCode
    {
      get { return _ErrorCode; }
      set { _ErrorCode = value; }
    }
    private string _Time = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private server.RespRegister _Register = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Register", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.RespRegister Register
    {
      get { return _Register; }
      set { _Register = value; }
    }
    private server.RespLogin _Login = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Login", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.RespLogin Login
    {
      get { return _Login; }
      set { _Login = value; }
    }
    private server.RespPraticeLevel _PraticeLevel = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"PraticeLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.RespPraticeLevel PraticeLevel
    {
      get { return _PraticeLevel; }
      set { _PraticeLevel = value; }
    }
    private server.RespActualCombat _ActualCombat = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ActualCombat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.RespActualCombat ActualCombat
    {
      get { return _ActualCombat; }
      set { _ActualCombat = value; }
    }
    private server.RespCancelMatch _CancelMatch = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"CancelMatch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.RespCancelMatch CancelMatch
    {
      get { return _CancelMatch; }
      set { _CancelMatch = value; }
    }
    private server.NotifyChooseHero _ChooseHero = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"ChooseHero", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.NotifyChooseHero ChooseHero
    {
      get { return _ChooseHero; }
      set { _ChooseHero = value; }
    }
    private server.NotifyReady _Ready = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"Ready", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.NotifyReady Ready
    {
      get { return _Ready; }
      set { _Ready = value; }
    }
    private server.NotifyEnterLevel _EnterLevel = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"EnterLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.NotifyEnterLevel EnterLevel
    {
      get { return _EnterLevel; }
      set { _EnterLevel = value; }
    }
    private server.NotifyRoleBorn _RoleBorn = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"RoleBorn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.NotifyRoleBorn RoleBorn
    {
      get { return _RoleBorn; }
      set { _RoleBorn = value; }
    }
    private server.NotifyRoleDie _RoleDie = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"RoleDie", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.NotifyRoleDie RoleDie
    {
      get { return _RoleDie; }
      set { _RoleDie = value; }
    }
    private server.NotifyRoleMove _RoleMove = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"RoleMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.NotifyRoleMove RoleMove
    {
      get { return _RoleMove; }
      set { _RoleMove = value; }
    }
    private server.NotifyRoleIdle _RoleIdle = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"RoleIdle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.NotifyRoleIdle RoleIdle
    {
      get { return _RoleIdle; }
      set { _RoleIdle = value; }
    }
    private server.NotifyRoleAttack _RoleAttack = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"RoleAttack", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.NotifyRoleAttack RoleAttack
    {
      get { return _RoleAttack; }
      set { _RoleAttack = value; }
    }
    private server.NotifyHPChange _HPChange = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"HPChange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public server.NotifyHPChange HPChange
    {
      get { return _HPChange; }
      set { _HPChange = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespRegister")]
  public partial class RespRegister : global::ProtoBuf.IExtensible
  {
    public RespRegister() {}
    
    private string _Account = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespLogin")]
  public partial class RespLogin : global::ProtoBuf.IExtensible
  {
    public RespLogin() {}
    
    private string _Account = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespPraticeLevel")]
  public partial class RespPraticeLevel : global::ProtoBuf.IExtensible
  {
    public RespPraticeLevel() {}
    
    private uint _PlayerNumber = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PlayerNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PlayerNumber
    {
      get { return _PlayerNumber; }
      set { _PlayerNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespActualCombat")]
  public partial class RespActualCombat : global::ProtoBuf.IExtensible
  {
    public RespActualCombat() {}
    
    private uint _PlayerNumber = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"PlayerNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PlayerNumber
    {
      get { return _PlayerNumber; }
      set { _PlayerNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespCancelMatch")]
  public partial class RespCancelMatch : global::ProtoBuf.IExtensible
  {
    public RespCancelMatch() {}
    
    private common.LevelType _LevelType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"LevelType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.LevelType LevelType
    {
      get { return _LevelType; }
      set { _LevelType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchAccountInfo")]
  public partial class MatchAccountInfo : global::ProtoBuf.IExtensible
  {
    public MatchAccountInfo() {}
    
    private uint _Index = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private common.RoleSide _RoleSide;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RoleSide", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.RoleSide RoleSide
    {
      get { return _RoleSide; }
      set { _RoleSide = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyChooseHero")]
  public partial class NotifyChooseHero : global::ProtoBuf.IExtensible
  {
    public NotifyChooseHero() {}
    
    private common.LevelType _LevelType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"LevelType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.LevelType LevelType
    {
      get { return _LevelType; }
      set { _LevelType = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _OptionalHeros = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"OptionalHeros", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> OptionalHeros
    {
      get { return _OptionalHeros; }
    }
  
    private readonly global::System.Collections.Generic.List<server.MatchAccountInfo> _Accounts = new global::System.Collections.Generic.List<server.MatchAccountInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Accounts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<server.MatchAccountInfo> Accounts
    {
      get { return _Accounts; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyReady")]
  public partial class NotifyReady : global::ProtoBuf.IExtensible
  {
    public NotifyReady() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private uint _HeroID = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"HeroID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HeroID
    {
      get { return _HeroID; }
      set { _HeroID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyEnterLevel")]
  public partial class NotifyEnterLevel : global::ProtoBuf.IExtensible
  {
    public NotifyEnterLevel() {}
    
    private common.LevelType _LevelType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"LevelType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public common.LevelType LevelType
    {
      get { return _LevelType; }
      set { _LevelType = value; }
    }
    private uint _PlayerNumber = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"PlayerNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint PlayerNumber
    {
      get { return _PlayerNumber; }
      set { _PlayerNumber = value; }
    }
    private readonly global::System.Collections.Generic.List<common.RoleData> _RoleList = new global::System.Collections.Generic.List<common.RoleData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"RoleList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.RoleData> RoleList
    {
      get { return _RoleList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyRoleBorn")]
  public partial class NotifyRoleBorn : global::ProtoBuf.IExtensible
  {
    public NotifyRoleBorn() {}
    
    private readonly global::System.Collections.Generic.List<common.RoleData> _RoleList = new global::System.Collections.Generic.List<common.RoleData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"RoleList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.RoleData> RoleList
    {
      get { return _RoleList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyRoleDie")]
  public partial class NotifyRoleDie : global::ProtoBuf.IExtensible
  {
    public NotifyRoleDie() {}
    
    private uint _globalRoleID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"globalRoleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint globalRoleID
    {
      get { return _globalRoleID; }
      set { _globalRoleID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyRoleMove")]
  public partial class NotifyRoleMove : global::ProtoBuf.IExtensible
  {
    public NotifyRoleMove() {}
    
    private uint _globalRoleID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"globalRoleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint globalRoleID
    {
      get { return _globalRoleID; }
      set { _globalRoleID = value; }
    }
    private common.Vector3 _position = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.Vector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyRoleIdle")]
  public partial class NotifyRoleIdle : global::ProtoBuf.IExtensible
  {
    public NotifyRoleIdle() {}
    
    private uint _globalRoleID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"globalRoleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint globalRoleID
    {
      get { return _globalRoleID; }
      set { _globalRoleID = value; }
    }
    private common.Vector3 _pos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.Vector3 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyRoleAttack")]
  public partial class NotifyRoleAttack : global::ProtoBuf.IExtensible
  {
    public NotifyRoleAttack() {}
    
    private uint _globalRoleID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"globalRoleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint globalRoleID
    {
      get { return _globalRoleID; }
      set { _globalRoleID = value; }
    }
    private uint _targetid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"targetid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint targetid
    {
      get { return _targetid; }
      set { _targetid = value; }
    }
    private uint _skillID = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"skillID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint skillID
    {
      get { return _skillID; }
      set { _skillID = value; }
    }
    private common.Vector3 _pos = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.Vector3 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyHPChange")]
  public partial class NotifyHPChange : global::ProtoBuf.IExtensible
  {
    public NotifyHPChange() {}
    
    private uint _targetid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint targetid
    {
      get { return _targetid; }
      set { _targetid = value; }
    }
    private int _hp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}